// <auto-generated />
using System;
using Lakbay.AgentOps.Oracle;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Lakbay.AgentOps.Oracle.Migrations
{
    [DbContext(typeof(CallLogDbContext))]
    partial class CallLogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lakbay.AgentOps.CallLogging.CallRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("AGENT_ID");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("BOOKING_ID");

                    b.Property<DateTime?>("CallEndUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CALL_END_UTC");

                    b.Property<DateTime>("CallStartUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CALL_START_UTC");

                    b.Property<string>("CallerPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)")
                        .HasColumnName("CALLER_PHONE_NUMBER");

                    b.Property<string>("MatchedCustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("MATCHED_CUSTOMER_NAME");

                    b.Property<int>("Outcome")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("OUTCOME");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CallStartUtc");

                    b.ToTable("CALL_RECORDS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
